//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.9032.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class rsp {
    
    private rspPhoto[] photoField;
    
    private string statField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("photo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhoto[] photo {
        get {
            return this.photoField;
        }
        set {
            this.photoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string stat {
        get {
            return this.statField;
        }
        set {
            this.statField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhoto {
    
    private string titleField;
    
    private string descriptionField;
    
    private string commentsField;
    
    private string notesField;
    
    private string tagsField;
    
    private rspPhotoOwner[] ownerField;
    
    private rspPhotoVisibility[] visibilityField;
    
    private rspPhotoDates[] datesField;
    
    private rspPhotoEditability[] editabilityField;
    
    private rspPhotoPubliceditability[] publiceditabilityField;
    
    private rspPhotoUsage[] usageField;
    
    private rspPhotoPeople[] peopleField;
    
    private rspPhotoUrlsUrl[][] urlsField;
    
    private string dateuploadedField;
    
    private string farmField;
    
    private string idField;
    
    private string isfavoriteField;
    
    private string licenseField;
    
    private string mediaField;
    
    private string originalformatField;
    
    private string originalsecretField;
    
    private string rotationField;
    
    private string safety_levelField;
    
    private string secretField;
    
    private string serverField;
    
    private string viewsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string comments {
        get {
            return this.commentsField;
        }
        set {
            this.commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string notes {
        get {
            return this.notesField;
        }
        set {
            this.notesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("owner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhotoOwner[] owner {
        get {
            return this.ownerField;
        }
        set {
            this.ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("visibility", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhotoVisibility[] visibility {
        get {
            return this.visibilityField;
        }
        set {
            this.visibilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dates", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhotoDates[] dates {
        get {
            return this.datesField;
        }
        set {
            this.datesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("editability", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhotoEditability[] editability {
        get {
            return this.editabilityField;
        }
        set {
            this.editabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("publiceditability", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhotoPubliceditability[] publiceditability {
        get {
            return this.publiceditabilityField;
        }
        set {
            this.publiceditabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("usage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhotoUsage[] usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("people", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhotoPeople[] people {
        get {
            return this.peopleField;
        }
        set {
            this.peopleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("url", typeof(rspPhotoUrlsUrl), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhotoUrlsUrl[][] urls {
        get {
            return this.urlsField;
        }
        set {
            this.urlsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dateuploaded {
        get {
            return this.dateuploadedField;
        }
        set {
            this.dateuploadedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string farm {
        get {
            return this.farmField;
        }
        set {
            this.farmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isfavorite {
        get {
            return this.isfavoriteField;
        }
        set {
            this.isfavoriteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string license {
        get {
            return this.licenseField;
        }
        set {
            this.licenseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string media {
        get {
            return this.mediaField;
        }
        set {
            this.mediaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string originalformat {
        get {
            return this.originalformatField;
        }
        set {
            this.originalformatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string originalsecret {
        get {
            return this.originalsecretField;
        }
        set {
            this.originalsecretField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rotation {
        get {
            return this.rotationField;
        }
        set {
            this.rotationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string safety_level {
        get {
            return this.safety_levelField;
        }
        set {
            this.safety_levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string secret {
        get {
            return this.secretField;
        }
        set {
            this.secretField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string server {
        get {
            return this.serverField;
        }
        set {
            this.serverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string views {
        get {
            return this.viewsField;
        }
        set {
            this.viewsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhotoOwner {
    
    private rspPhotoOwnerGift[] giftField;
    
    private string iconfarmField;
    
    private string iconserverField;
    
    private string locationField;
    
    private string nsidField;
    
    private string path_aliasField;
    
    private string realnameField;
    
    private string usernameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("gift", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhotoOwnerGift[] gift {
        get {
            return this.giftField;
        }
        set {
            this.giftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconfarm {
        get {
            return this.iconfarmField;
        }
        set {
            this.iconfarmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string iconserver {
        get {
            return this.iconserverField;
        }
        set {
            this.iconserverField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nsid {
        get {
            return this.nsidField;
        }
        set {
            this.nsidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path_alias {
        get {
            return this.path_aliasField;
        }
        set {
            this.path_aliasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string realname {
        get {
            return this.realnameField;
        }
        set {
            this.realnameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhotoOwnerGift {
    
    private rspPhotoOwnerGiftEligible_durations[] eligible_durationsField;
    
    private string gift_eligibleField;
    
    private string new_flowField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("eligible_durations", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public rspPhotoOwnerGiftEligible_durations[] eligible_durations {
        get {
            return this.eligible_durationsField;
        }
        set {
            this.eligible_durationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gift_eligible {
        get {
            return this.gift_eligibleField;
        }
        set {
            this.gift_eligibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string new_flow {
        get {
            return this.new_flowField;
        }
        set {
            this.new_flowField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhotoOwnerGiftEligible_durations {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhotoVisibility {
    
    private string isfamilyField;
    
    private string isfriendField;
    
    private string ispublicField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isfamily {
        get {
            return this.isfamilyField;
        }
        set {
            this.isfamilyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string isfriend {
        get {
            return this.isfriendField;
        }
        set {
            this.isfriendField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ispublic {
        get {
            return this.ispublicField;
        }
        set {
            this.ispublicField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhotoDates {
    
    private string lastupdateField;
    
    private string postedField;
    
    private string takenField;
    
    private string takengranularityField;
    
    private string takenunknownField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lastupdate {
        get {
            return this.lastupdateField;
        }
        set {
            this.lastupdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string posted {
        get {
            return this.postedField;
        }
        set {
            this.postedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taken {
        get {
            return this.takenField;
        }
        set {
            this.takenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string takengranularity {
        get {
            return this.takengranularityField;
        }
        set {
            this.takengranularityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string takenunknown {
        get {
            return this.takenunknownField;
        }
        set {
            this.takenunknownField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhotoEditability {
    
    private string canaddmetaField;
    
    private string cancommentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string canaddmeta {
        get {
            return this.canaddmetaField;
        }
        set {
            this.canaddmetaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cancomment {
        get {
            return this.cancommentField;
        }
        set {
            this.cancommentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhotoPubliceditability {
    
    private string canaddmetaField;
    
    private string cancommentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string canaddmeta {
        get {
            return this.canaddmetaField;
        }
        set {
            this.canaddmetaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cancomment {
        get {
            return this.cancommentField;
        }
        set {
            this.cancommentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhotoUsage {
    
    private string canblogField;
    
    private string candownloadField;
    
    private string canprintField;
    
    private string canshareField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string canblog {
        get {
            return this.canblogField;
        }
        set {
            this.canblogField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string candownload {
        get {
            return this.candownloadField;
        }
        set {
            this.candownloadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string canprint {
        get {
            return this.canprintField;
        }
        set {
            this.canprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string canshare {
        get {
            return this.canshareField;
        }
        set {
            this.canshareField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhotoPeople {
    
    private string haspeopleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string haspeople {
        get {
            return this.haspeopleField;
        }
        set {
            this.haspeopleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class rspPhotoUrlsUrl {
    
    private string typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private rsp[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("rsp")]
    public rsp[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
